// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rpact_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mvnprd
NumericVector mvnprd(NumericVector a, NumericVector b, NumericVector bpd, float eps, IntegerVector inf, int ierc, float hinc);
RcppExport SEXP _rpact_mvnprd(SEXP aSEXP, SEXP bSEXP, SEXP bpdSEXP, SEXP epsSEXP, SEXP infSEXP, SEXP iercSEXP, SEXP hincSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bpd(bpdSEXP);
    Rcpp::traits::input_parameter< float >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inf(infSEXP);
    Rcpp::traits::input_parameter< int >::type ierc(iercSEXP);
    Rcpp::traits::input_parameter< float >::type hinc(hincSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnprd(a, b, bpd, eps, inf, ierc, hinc));
    return rcpp_result_gen;
END_RCPP
}
// mvstud
NumericVector mvstud(int ndf, NumericVector a, NumericVector b, NumericVector bpd, NumericVector d, float eps, IntegerVector inf, int ierc, float hnc);
RcppExport SEXP _rpact_mvstud(SEXP ndfSEXP, SEXP aSEXP, SEXP bSEXP, SEXP bpdSEXP, SEXP dSEXP, SEXP epsSEXP, SEXP infSEXP, SEXP iercSEXP, SEXP hncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ndf(ndfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bpd(bpdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< float >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type inf(infSEXP);
    Rcpp::traits::input_parameter< int >::type ierc(iercSEXP);
    Rcpp::traits::input_parameter< float >::type hnc(hncSEXP);
    rcpp_result_gen = Rcpp::wrap(mvstud(ndf, a, b, bpd, d, eps, inf, ierc, hnc));
    return rcpp_result_gen;
END_RCPP
}
// as251Normal
double as251Normal(NumericVector lower, NumericVector upper, NumericMatrix sigma, double eps, String errorControl, double intervalSimpsonsRule);
RcppExport SEXP _rpact_as251Normal(SEXP lowerSEXP, SEXP upperSEXP, SEXP sigmaSEXP, SEXP epsSEXP, SEXP errorControlSEXP, SEXP intervalSimpsonsRuleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< String >::type errorControl(errorControlSEXP);
    Rcpp::traits::input_parameter< double >::type intervalSimpsonsRule(intervalSimpsonsRuleSEXP);
    rcpp_result_gen = Rcpp::wrap(as251Normal(lower, upper, sigma, eps, errorControl, intervalSimpsonsRule));
    return rcpp_result_gen;
END_RCPP
}
// estimate_nb
SEXP estimate_nb(NumericVector counts1, NumericVector counts2, NumericVector t1, NumericVector t2);
RcppExport SEXP _rpact_estimate_nb(SEXP counts1SEXP, SEXP counts2SEXP, SEXP t1SEXP, SEXP t2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts1(counts1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type counts2(counts2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t2(t2SEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_nb(counts1, counts2, t1, t2));
    return rcpp_result_gen;
END_RCPP
}
// getFisherCombinationSizeCpp
double getFisherCombinationSizeCpp(double kMax, NumericVector alpha0Vec, NumericVector criticalValues, NumericVector tVec, NumericVector cases);
RcppExport SEXP _rpact_getFisherCombinationSizeCpp(SEXP kMaxSEXP, SEXP alpha0VecSEXP, SEXP criticalValuesSEXP, SEXP tVecSEXP, SEXP casesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha0Vec(alpha0VecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type criticalValues(criticalValuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tVec(tVecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cases(casesSEXP);
    rcpp_result_gen = Rcpp::wrap(getFisherCombinationSizeCpp(kMax, alpha0Vec, criticalValues, tVec, cases));
    return rcpp_result_gen;
END_RCPP
}
// getSimulatedAlphaCpp
double getSimulatedAlphaCpp(int kMax, NumericVector alpha0, NumericVector criticalValues, NumericVector tVec, int iterations);
RcppExport SEXP _rpact_getSimulatedAlphaCpp(SEXP kMaxSEXP, SEXP alpha0SEXP, SEXP criticalValuesSEXP, SEXP tVecSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type criticalValues(criticalValuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tVec(tVecSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(getSimulatedAlphaCpp(kMax, alpha0, criticalValues, tVec, iterations));
    return rcpp_result_gen;
END_RCPP
}
// getFisherCombinationCasesCpp
NumericVector getFisherCombinationCasesCpp(int kMax, NumericVector tVec);
RcppExport SEXP _rpact_getFisherCombinationCasesCpp(SEXP kMaxSEXP, SEXP tVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tVec(tVecSEXP);
    rcpp_result_gen = Rcpp::wrap(getFisherCombinationCasesCpp(kMax, tVec));
    return rcpp_result_gen;
END_RCPP
}
// getDesignFisherTryCpp
List getDesignFisherTryCpp(int kMax, double alpha, double tolerance, NumericVector criticalValues, NumericVector scale, NumericVector alpha0Vec, NumericVector userAlphaSpending, String method);
RcppExport SEXP _rpact_getDesignFisherTryCpp(SEXP kMaxSEXP, SEXP alphaSEXP, SEXP toleranceSEXP, SEXP criticalValuesSEXP, SEXP scaleSEXP, SEXP alpha0VecSEXP, SEXP userAlphaSpendingSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type criticalValues(criticalValuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha0Vec(alpha0VecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type userAlphaSpending(userAlphaSpendingSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignFisherTryCpp(kMax, alpha, tolerance, criticalValues, scale, alpha0Vec, userAlphaSpending, method));
    return rcpp_result_gen;
END_RCPP
}
// getGroupSequentialProbabilitiesCpp
NumericMatrix getGroupSequentialProbabilitiesCpp(NumericMatrix decisionMatrix, NumericVector informationRates);
RcppExport SEXP _rpact_getGroupSequentialProbabilitiesCpp(SEXP decisionMatrixSEXP, SEXP informationRatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type decisionMatrix(decisionMatrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    rcpp_result_gen = Rcpp::wrap(getGroupSequentialProbabilitiesCpp(decisionMatrix, informationRates));
    return rcpp_result_gen;
END_RCPP
}
// getDesignGroupSequentialPampallonaTsiatisCpp
List getDesignGroupSequentialPampallonaTsiatisCpp(double tolerance, double beta, double alpha, double kMax, double deltaPT0, double deltaPT1, NumericVector informationRates, int sided, bool bindingFutility);
RcppExport SEXP _rpact_getDesignGroupSequentialPampallonaTsiatisCpp(SEXP toleranceSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP kMaxSEXP, SEXP deltaPT0SEXP, SEXP deltaPT1SEXP, SEXP informationRatesSEXP, SEXP sidedSEXP, SEXP bindingFutilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< double >::type deltaPT0(deltaPT0SEXP);
    Rcpp::traits::input_parameter< double >::type deltaPT1(deltaPT1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< int >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< bool >::type bindingFutility(bindingFutilitySEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignGroupSequentialPampallonaTsiatisCpp(tolerance, beta, alpha, kMax, deltaPT0, deltaPT1, informationRates, sided, bindingFutility));
    return rcpp_result_gen;
END_RCPP
}
// getDesignGroupSequentialUserDefinedAlphaSpendingCpp
NumericVector getDesignGroupSequentialUserDefinedAlphaSpendingCpp(int kMax, NumericVector userAlphaSpending, double sided, NumericVector informationRates, bool bindingFutility, NumericVector futilityBounds, double tolerance);
RcppExport SEXP _rpact_getDesignGroupSequentialUserDefinedAlphaSpendingCpp(SEXP kMaxSEXP, SEXP userAlphaSpendingSEXP, SEXP sidedSEXP, SEXP informationRatesSEXP, SEXP bindingFutilitySEXP, SEXP futilityBoundsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type userAlphaSpending(userAlphaSpendingSEXP);
    Rcpp::traits::input_parameter< double >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< bool >::type bindingFutility(bindingFutilitySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type futilityBounds(futilityBoundsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignGroupSequentialUserDefinedAlphaSpendingCpp(kMax, userAlphaSpending, sided, informationRates, bindingFutility, futilityBounds, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// getDesignGroupSequentialAlphaSpendingCpp
NumericVector getDesignGroupSequentialAlphaSpendingCpp(int kMax, double alpha, double gammaA, String typeOfDesign, double sided, NumericVector informationRates, bool bindingFutility, NumericVector futilityBounds, double tolerance);
RcppExport SEXP _rpact_getDesignGroupSequentialAlphaSpendingCpp(SEXP kMaxSEXP, SEXP alphaSEXP, SEXP gammaASEXP, SEXP typeOfDesignSEXP, SEXP sidedSEXP, SEXP informationRatesSEXP, SEXP bindingFutilitySEXP, SEXP futilityBoundsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gammaA(gammaASEXP);
    Rcpp::traits::input_parameter< String >::type typeOfDesign(typeOfDesignSEXP);
    Rcpp::traits::input_parameter< double >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< bool >::type bindingFutility(bindingFutilitySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type futilityBounds(futilityBoundsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignGroupSequentialAlphaSpendingCpp(kMax, alpha, gammaA, typeOfDesign, sided, informationRates, bindingFutility, futilityBounds, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// getDesignGroupSequentialDeltaWTCpp
NumericVector getDesignGroupSequentialDeltaWTCpp(int kMax, double alpha, double sided, NumericVector informationRates, bool bindingFutility, NumericVector futilityBounds, double tolerance, double deltaWT);
RcppExport SEXP _rpact_getDesignGroupSequentialDeltaWTCpp(SEXP kMaxSEXP, SEXP alphaSEXP, SEXP sidedSEXP, SEXP informationRatesSEXP, SEXP bindingFutilitySEXP, SEXP futilityBoundsSEXP, SEXP toleranceSEXP, SEXP deltaWTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< bool >::type bindingFutility(bindingFutilitySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type futilityBounds(futilityBoundsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type deltaWT(deltaWTSEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignGroupSequentialDeltaWTCpp(kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance, deltaWT));
    return rcpp_result_gen;
END_RCPP
}
// getDesignGroupSequentialPocockCpp
NumericVector getDesignGroupSequentialPocockCpp(int kMax, double alpha, double sided, NumericVector informationRates, bool bindingFutility, NumericVector futilityBounds, double tolerance);
RcppExport SEXP _rpact_getDesignGroupSequentialPocockCpp(SEXP kMaxSEXP, SEXP alphaSEXP, SEXP sidedSEXP, SEXP informationRatesSEXP, SEXP bindingFutilitySEXP, SEXP futilityBoundsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< bool >::type bindingFutility(bindingFutilitySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type futilityBounds(futilityBoundsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignGroupSequentialPocockCpp(kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// getDesignGroupSequentialOBrienAndFlemingCpp
NumericVector getDesignGroupSequentialOBrienAndFlemingCpp(int kMax, double alpha, double sided, NumericVector informationRates, bool bindingFutility, NumericVector futilityBounds, double tolerance);
RcppExport SEXP _rpact_getDesignGroupSequentialOBrienAndFlemingCpp(SEXP kMaxSEXP, SEXP alphaSEXP, SEXP sidedSEXP, SEXP informationRatesSEXP, SEXP bindingFutilitySEXP, SEXP futilityBoundsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< bool >::type bindingFutility(bindingFutilitySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type futilityBounds(futilityBoundsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignGroupSequentialOBrienAndFlemingCpp(kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// getDesignGroupSequentialBetaSpendingCpp
List getDesignGroupSequentialBetaSpendingCpp(NumericVector criticalValues, int kMax, NumericVector userAlphaSpending, NumericVector userBetaSpending, NumericVector informationRates, bool bindingFutility, double tolerance, String typeOfDesign, String typeBetaSpending, double gammaA, double gammaB, double alpha, double beta, double sided, bool betaAdjustment, bool twoSidedPower);
RcppExport SEXP _rpact_getDesignGroupSequentialBetaSpendingCpp(SEXP criticalValuesSEXP, SEXP kMaxSEXP, SEXP userAlphaSpendingSEXP, SEXP userBetaSpendingSEXP, SEXP informationRatesSEXP, SEXP bindingFutilitySEXP, SEXP toleranceSEXP, SEXP typeOfDesignSEXP, SEXP typeBetaSpendingSEXP, SEXP gammaASEXP, SEXP gammaBSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP sidedSEXP, SEXP betaAdjustmentSEXP, SEXP twoSidedPowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type criticalValues(criticalValuesSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type userAlphaSpending(userAlphaSpendingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type userBetaSpending(userBetaSpendingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< bool >::type bindingFutility(bindingFutilitySEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< String >::type typeOfDesign(typeOfDesignSEXP);
    Rcpp::traits::input_parameter< String >::type typeBetaSpending(typeBetaSpendingSEXP);
    Rcpp::traits::input_parameter< double >::type gammaA(gammaASEXP);
    Rcpp::traits::input_parameter< double >::type gammaB(gammaBSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< bool >::type betaAdjustment(betaAdjustmentSEXP);
    Rcpp::traits::input_parameter< bool >::type twoSidedPower(twoSidedPowerSEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignGroupSequentialBetaSpendingCpp(criticalValues, kMax, userAlphaSpending, userBetaSpending, informationRates, bindingFutility, tolerance, typeOfDesign, typeBetaSpending, gammaA, gammaB, alpha, beta, sided, betaAdjustment, twoSidedPower));
    return rcpp_result_gen;
END_RCPP
}
// getDesignGroupSequentialUserDefinedBetaSpendingCpp
List getDesignGroupSequentialUserDefinedBetaSpendingCpp(NumericVector criticalValues, int kMax, NumericVector userAlphaSpending, NumericVector userBetaSpending, double sided, NumericVector informationRates, bool bindingFutility, double tolerance, String typeOfDesign, double gammaA, double alpha, bool betaAdjustment, bool twoSidedPower);
RcppExport SEXP _rpact_getDesignGroupSequentialUserDefinedBetaSpendingCpp(SEXP criticalValuesSEXP, SEXP kMaxSEXP, SEXP userAlphaSpendingSEXP, SEXP userBetaSpendingSEXP, SEXP sidedSEXP, SEXP informationRatesSEXP, SEXP bindingFutilitySEXP, SEXP toleranceSEXP, SEXP typeOfDesignSEXP, SEXP gammaASEXP, SEXP alphaSEXP, SEXP betaAdjustmentSEXP, SEXP twoSidedPowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type criticalValues(criticalValuesSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type userAlphaSpending(userAlphaSpendingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type userBetaSpending(userBetaSpendingSEXP);
    Rcpp::traits::input_parameter< double >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< bool >::type bindingFutility(bindingFutilitySEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< String >::type typeOfDesign(typeOfDesignSEXP);
    Rcpp::traits::input_parameter< double >::type gammaA(gammaASEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type betaAdjustment(betaAdjustmentSEXP);
    Rcpp::traits::input_parameter< bool >::type twoSidedPower(twoSidedPowerSEXP);
    rcpp_result_gen = Rcpp::wrap(getDesignGroupSequentialUserDefinedBetaSpendingCpp(criticalValues, kMax, userAlphaSpending, userBetaSpending, sided, informationRates, bindingFutility, tolerance, typeOfDesign, gammaA, alpha, betaAdjustment, twoSidedPower));
    return rcpp_result_gen;
END_RCPP
}
// getSimulationMeansLoopCpp
List getSimulationMeansLoopCpp(NumericVector alternative, int kMax, int maxNumberOfIterations, int designNumber, NumericVector informationRates, NumericVector futilityBounds, NumericVector alpha0Vec, NumericVector criticalValues, bool meanRatio, double thetaH0, NumericVector stDev, int groups, bool normalApproximation, NumericVector plannedSubjects, bool directionUpper, NumericVector allocationRatioPlanned, NumericVector minNumberOfSubjectsPerStage, NumericVector maxNumberOfSubjectsPerStage, double conditionalPower, double thetaH1, NumericVector stDevH1, int calcSubjectsFunctionType, Nullable<Function> calcSubjectsFunctionR, SEXP calcSubjectsFunctionCpp);
RcppExport SEXP _rpact_getSimulationMeansLoopCpp(SEXP alternativeSEXP, SEXP kMaxSEXP, SEXP maxNumberOfIterationsSEXP, SEXP designNumberSEXP, SEXP informationRatesSEXP, SEXP futilityBoundsSEXP, SEXP alpha0VecSEXP, SEXP criticalValuesSEXP, SEXP meanRatioSEXP, SEXP thetaH0SEXP, SEXP stDevSEXP, SEXP groupsSEXP, SEXP normalApproximationSEXP, SEXP plannedSubjectsSEXP, SEXP directionUpperSEXP, SEXP allocationRatioPlannedSEXP, SEXP minNumberOfSubjectsPerStageSEXP, SEXP maxNumberOfSubjectsPerStageSEXP, SEXP conditionalPowerSEXP, SEXP thetaH1SEXP, SEXP stDevH1SEXP, SEXP calcSubjectsFunctionTypeSEXP, SEXP calcSubjectsFunctionRSEXP, SEXP calcSubjectsFunctionCppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type alternative(alternativeSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfIterations(maxNumberOfIterationsSEXP);
    Rcpp::traits::input_parameter< int >::type designNumber(designNumberSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type futilityBounds(futilityBoundsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha0Vec(alpha0VecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type criticalValues(criticalValuesSEXP);
    Rcpp::traits::input_parameter< bool >::type meanRatio(meanRatioSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH0(thetaH0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stDev(stDevSEXP);
    Rcpp::traits::input_parameter< int >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< bool >::type normalApproximation(normalApproximationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedSubjects(plannedSubjectsSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type allocationRatioPlanned(allocationRatioPlannedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfSubjectsPerStage(minNumberOfSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfSubjectsPerStage(maxNumberOfSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< double >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH1(thetaH1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stDevH1(stDevH1SEXP);
    Rcpp::traits::input_parameter< int >::type calcSubjectsFunctionType(calcSubjectsFunctionTypeSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type calcSubjectsFunctionR(calcSubjectsFunctionRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type calcSubjectsFunctionCpp(calcSubjectsFunctionCppSEXP);
    rcpp_result_gen = Rcpp::wrap(getSimulationMeansLoopCpp(alternative, kMax, maxNumberOfIterations, designNumber, informationRates, futilityBounds, alpha0Vec, criticalValues, meanRatio, thetaH0, stDev, groups, normalApproximation, plannedSubjects, directionUpper, allocationRatioPlanned, minNumberOfSubjectsPerStage, maxNumberOfSubjectsPerStage, conditionalPower, thetaH1, stDevH1, calcSubjectsFunctionType, calcSubjectsFunctionR, calcSubjectsFunctionCpp));
    return rcpp_result_gen;
END_RCPP
}
// getSimulationRatesCpp
List getSimulationRatesCpp(int kMax, NumericVector informationRates, NumericVector criticalValues, NumericVector pi1, double pi2, int maxNumberOfIterations, int designNumber, int groups, NumericVector futilityBounds, NumericVector alpha0Vec, NumericVector minNumberOfSubjectsPerStage, NumericVector maxNumberOfSubjectsPerStage, NumericVector conditionalPower, NumericVector pi1H1, NumericVector pi2H1, bool normalApproximation, NumericVector plannedSubjects, bool directionUpper, NumericVector allocationRatioPlanned, bool riskRatio, double thetaH0, int calcSubjectsFunctionType, Nullable<Function> calcSubjectsFunctionR, SEXP calcSubjectsFunctionCpp);
RcppExport SEXP _rpact_getSimulationRatesCpp(SEXP kMaxSEXP, SEXP informationRatesSEXP, SEXP criticalValuesSEXP, SEXP pi1SEXP, SEXP pi2SEXP, SEXP maxNumberOfIterationsSEXP, SEXP designNumberSEXP, SEXP groupsSEXP, SEXP futilityBoundsSEXP, SEXP alpha0VecSEXP, SEXP minNumberOfSubjectsPerStageSEXP, SEXP maxNumberOfSubjectsPerStageSEXP, SEXP conditionalPowerSEXP, SEXP pi1H1SEXP, SEXP pi2H1SEXP, SEXP normalApproximationSEXP, SEXP plannedSubjectsSEXP, SEXP directionUpperSEXP, SEXP allocationRatioPlannedSEXP, SEXP riskRatioSEXP, SEXP thetaH0SEXP, SEXP calcSubjectsFunctionTypeSEXP, SEXP calcSubjectsFunctionRSEXP, SEXP calcSubjectsFunctionCppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type criticalValues(criticalValuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi1(pi1SEXP);
    Rcpp::traits::input_parameter< double >::type pi2(pi2SEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfIterations(maxNumberOfIterationsSEXP);
    Rcpp::traits::input_parameter< int >::type designNumber(designNumberSEXP);
    Rcpp::traits::input_parameter< int >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type futilityBounds(futilityBoundsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha0Vec(alpha0VecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfSubjectsPerStage(minNumberOfSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfSubjectsPerStage(maxNumberOfSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi1H1(pi1H1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi2H1(pi2H1SEXP);
    Rcpp::traits::input_parameter< bool >::type normalApproximation(normalApproximationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedSubjects(plannedSubjectsSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type allocationRatioPlanned(allocationRatioPlannedSEXP);
    Rcpp::traits::input_parameter< bool >::type riskRatio(riskRatioSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH0(thetaH0SEXP);
    Rcpp::traits::input_parameter< int >::type calcSubjectsFunctionType(calcSubjectsFunctionTypeSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type calcSubjectsFunctionR(calcSubjectsFunctionRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type calcSubjectsFunctionCpp(calcSubjectsFunctionCppSEXP);
    rcpp_result_gen = Rcpp::wrap(getSimulationRatesCpp(kMax, informationRates, criticalValues, pi1, pi2, maxNumberOfIterations, designNumber, groups, futilityBounds, alpha0Vec, minNumberOfSubjectsPerStage, maxNumberOfSubjectsPerStage, conditionalPower, pi1H1, pi2H1, normalApproximation, plannedSubjects, directionUpper, allocationRatioPlanned, riskRatio, thetaH0, calcSubjectsFunctionType, calcSubjectsFunctionR, calcSubjectsFunctionCpp));
    return rcpp_result_gen;
END_RCPP
}
// logRankTest
List logRankTest(NumericVector accrualTime, NumericVector survivalTime, NumericVector dropoutTime, IntegerVector treatmentGroup, double time, bool directionUpper, double thetaH0, bool returnRawData);
RcppExport SEXP _rpact_logRankTest(SEXP accrualTimeSEXP, SEXP survivalTimeSEXP, SEXP dropoutTimeSEXP, SEXP treatmentGroupSEXP, SEXP timeSEXP, SEXP directionUpperSEXP, SEXP thetaH0SEXP, SEXP returnRawDataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type accrualTime(accrualTimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type survivalTime(survivalTimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dropoutTime(dropoutTimeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type treatmentGroup(treatmentGroupSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH0(thetaH0SEXP);
    Rcpp::traits::input_parameter< bool >::type returnRawData(returnRawDataSEXP);
    rcpp_result_gen = Rcpp::wrap(logRankTest(accrualTime, survivalTime, dropoutTime, treatmentGroup, time, directionUpper, thetaH0, returnRawData));
    return rcpp_result_gen;
END_RCPP
}
// getSimulationSurvivalCpp
List getSimulationSurvivalCpp(int designNumber, int kMax, int sided, NumericVector criticalValues, NumericVector informationRates, double conditionalPower, NumericVector plannedEvents, double thetaH1, NumericVector minNumberOfEventsPerStage, NumericVector maxNumberOfEventsPerStage, bool directionUpper, double allocationRatioPlanned, NumericVector accrualTime, IntegerVector treatmentGroup, double thetaH0, NumericVector futilityBounds, NumericVector alpha0Vec, NumericVector pi1Vec, double pi2, double eventTime, NumericVector piecewiseSurvivalTime, NumericVector cdfValues1, NumericVector cdfValues2, NumericVector lambdaVec1, NumericVector lambdaVec2, NumericVector phi, int maxNumberOfSubjects, int maxNumberOfIterations, int maxNumberOfRawDatasetsPerStage, double kappa, int calcEventsFunctionType, Nullable<Function> calcEventsFunctionR, SEXP calcEventsFunctionCpp);
RcppExport SEXP _rpact_getSimulationSurvivalCpp(SEXP designNumberSEXP, SEXP kMaxSEXP, SEXP sidedSEXP, SEXP criticalValuesSEXP, SEXP informationRatesSEXP, SEXP conditionalPowerSEXP, SEXP plannedEventsSEXP, SEXP thetaH1SEXP, SEXP minNumberOfEventsPerStageSEXP, SEXP maxNumberOfEventsPerStageSEXP, SEXP directionUpperSEXP, SEXP allocationRatioPlannedSEXP, SEXP accrualTimeSEXP, SEXP treatmentGroupSEXP, SEXP thetaH0SEXP, SEXP futilityBoundsSEXP, SEXP alpha0VecSEXP, SEXP pi1VecSEXP, SEXP pi2SEXP, SEXP eventTimeSEXP, SEXP piecewiseSurvivalTimeSEXP, SEXP cdfValues1SEXP, SEXP cdfValues2SEXP, SEXP lambdaVec1SEXP, SEXP lambdaVec2SEXP, SEXP phiSEXP, SEXP maxNumberOfSubjectsSEXP, SEXP maxNumberOfIterationsSEXP, SEXP maxNumberOfRawDatasetsPerStageSEXP, SEXP kappaSEXP, SEXP calcEventsFunctionTypeSEXP, SEXP calcEventsFunctionRSEXP, SEXP calcEventsFunctionCppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type designNumber(designNumberSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< int >::type sided(sidedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type criticalValues(criticalValuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type informationRates(informationRatesSEXP);
    Rcpp::traits::input_parameter< double >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedEvents(plannedEventsSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH1(thetaH1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfEventsPerStage(minNumberOfEventsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfEventsPerStage(maxNumberOfEventsPerStageSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< double >::type allocationRatioPlanned(allocationRatioPlannedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type accrualTime(accrualTimeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type treatmentGroup(treatmentGroupSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH0(thetaH0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type futilityBounds(futilityBoundsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha0Vec(alpha0VecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi1Vec(pi1VecSEXP);
    Rcpp::traits::input_parameter< double >::type pi2(pi2SEXP);
    Rcpp::traits::input_parameter< double >::type eventTime(eventTimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piecewiseSurvivalTime(piecewiseSurvivalTimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cdfValues1(cdfValues1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cdfValues2(cdfValues2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambdaVec1(lambdaVec1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambdaVec2(lambdaVec2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfSubjects(maxNumberOfSubjectsSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfIterations(maxNumberOfIterationsSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfRawDatasetsPerStage(maxNumberOfRawDatasetsPerStageSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< int >::type calcEventsFunctionType(calcEventsFunctionTypeSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type calcEventsFunctionR(calcEventsFunctionRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type calcEventsFunctionCpp(calcEventsFunctionCppSEXP);
    rcpp_result_gen = Rcpp::wrap(getSimulationSurvivalCpp(designNumber, kMax, sided, criticalValues, informationRates, conditionalPower, plannedEvents, thetaH1, minNumberOfEventsPerStage, maxNumberOfEventsPerStage, directionUpper, allocationRatioPlanned, accrualTime, treatmentGroup, thetaH0, futilityBounds, alpha0Vec, pi1Vec, pi2, eventTime, piecewiseSurvivalTime, cdfValues1, cdfValues2, lambdaVec1, lambdaVec2, phi, maxNumberOfSubjects, maxNumberOfIterations, maxNumberOfRawDatasetsPerStage, kappa, calcEventsFunctionType, calcEventsFunctionR, calcEventsFunctionCpp));
    return rcpp_result_gen;
END_RCPP
}
// selectPopulations
LogicalVector selectPopulations(NumericVector effectVector, std::string typeOfSelection, double epsilonValue, int rValue, double threshold);
RcppExport SEXP _rpact_selectPopulations(SEXP effectVectorSEXP, SEXP typeOfSelectionSEXP, SEXP epsilonValueSEXP, SEXP rValueSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type effectVector(effectVectorSEXP);
    Rcpp::traits::input_parameter< std::string >::type typeOfSelection(typeOfSelectionSEXP);
    Rcpp::traits::input_parameter< double >::type epsilonValue(epsilonValueSEXP);
    Rcpp::traits::input_parameter< int >::type rValue(rValueSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(selectPopulations(effectVector, typeOfSelection, epsilonValue, rValue, threshold));
    return rcpp_result_gen;
END_RCPP
}
// performClosedCombinationTestForSimulationEnrichment
List performClosedCombinationTestForSimulationEnrichment(List stageResults, Environment design, IntegerMatrix indices, std::string intersectionTest, std::string successCriterion);
RcppExport SEXP _rpact_performClosedCombinationTestForSimulationEnrichment(SEXP stageResultsSEXP, SEXP designSEXP, SEXP indicesSEXP, SEXP intersectionTestSEXP, SEXP successCriterionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type stageResults(stageResultsSEXP);
    Rcpp::traits::input_parameter< Environment >::type design(designSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< std::string >::type intersectionTest(intersectionTestSEXP);
    Rcpp::traits::input_parameter< std::string >::type successCriterion(successCriterionSEXP);
    rcpp_result_gen = Rcpp::wrap(performClosedCombinationTestForSimulationEnrichment(stageResults, design, indices, intersectionTest, successCriterion));
    return rcpp_result_gen;
END_RCPP
}
// createSelectedSubsets
LogicalVector createSelectedSubsets(LogicalVector selectedPopulationsAtStagek);
RcppExport SEXP _rpact_createSelectedSubsets(SEXP selectedPopulationsAtStagekSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type selectedPopulationsAtStagek(selectedPopulationsAtStagekSEXP);
    rcpp_result_gen = Rcpp::wrap(createSelectedSubsets(selectedPopulationsAtStagek));
    return rcpp_result_gen;
END_RCPP
}
// createSubGroups
CharacterVector createSubGroups(int gMax);
RcppExport SEXP _rpact_createSubGroups(SEXP gMaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type gMax(gMaxSEXP);
    rcpp_result_gen = Rcpp::wrap(createSubGroups(gMax));
    return rcpp_result_gen;
END_RCPP
}
// createSubGroupsFromPopulation
CharacterVector createSubGroupsFromPopulation(int gMax, int subPopulation);
RcppExport SEXP _rpact_createSubGroupsFromPopulation(SEXP gMaxSEXP, SEXP subPopulationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type gMax(gMaxSEXP);
    Rcpp::traits::input_parameter< int >::type subPopulation(subPopulationSEXP);
    rcpp_result_gen = Rcpp::wrap(createSubGroupsFromPopulation(gMax, subPopulation));
    return rcpp_result_gen;
END_RCPP
}
// logRankTestEnrichment
List logRankTestEnrichment(int gMax, DataFrame survivalDataSet, double time, int subPopulation, bool stratifiedAnalysis, bool directionUpper, double thetaH0);
RcppExport SEXP _rpact_logRankTestEnrichment(SEXP gMaxSEXP, SEXP survivalDataSetSEXP, SEXP timeSEXP, SEXP subPopulationSEXP, SEXP stratifiedAnalysisSEXP, SEXP directionUpperSEXP, SEXP thetaH0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type gMax(gMaxSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type survivalDataSet(survivalDataSetSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type subPopulation(subPopulationSEXP);
    Rcpp::traits::input_parameter< bool >::type stratifiedAnalysis(stratifiedAnalysisSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH0(thetaH0SEXP);
    rcpp_result_gen = Rcpp::wrap(logRankTestEnrichment(gMax, survivalDataSet, time, subPopulation, stratifiedAnalysis, directionUpper, thetaH0));
    return rcpp_result_gen;
END_RCPP
}
// getSimulationSurvivalEnrichmentStageEvents
double getSimulationSurvivalEnrichmentStageEvents(int stage, bool directionUpper, double conditionalPower, NumericVector conditionalCriticalValue, NumericVector plannedEvents, NumericVector allocationRatioPlanned, LogicalMatrix selectedPopulations, double thetaH1, NumericMatrix overallEffects, NumericVector minNumberOfEventsPerStage, NumericVector maxNumberOfEventsPerStage);
RcppExport SEXP _rpact_getSimulationSurvivalEnrichmentStageEvents(SEXP stageSEXP, SEXP directionUpperSEXP, SEXP conditionalPowerSEXP, SEXP conditionalCriticalValueSEXP, SEXP plannedEventsSEXP, SEXP allocationRatioPlannedSEXP, SEXP selectedPopulationsSEXP, SEXP thetaH1SEXP, SEXP overallEffectsSEXP, SEXP minNumberOfEventsPerStageSEXP, SEXP maxNumberOfEventsPerStageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type stage(stageSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< double >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type conditionalCriticalValue(conditionalCriticalValueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedEvents(plannedEventsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type allocationRatioPlanned(allocationRatioPlannedSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type selectedPopulations(selectedPopulationsSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH1(thetaH1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type overallEffects(overallEffectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfEventsPerStage(minNumberOfEventsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfEventsPerStage(maxNumberOfEventsPerStageSEXP);
    rcpp_result_gen = Rcpp::wrap(getSimulationSurvivalEnrichmentStageEvents(stage, directionUpper, conditionalPower, conditionalCriticalValue, plannedEvents, allocationRatioPlanned, selectedPopulations, thetaH1, overallEffects, minNumberOfEventsPerStage, maxNumberOfEventsPerStage));
    return rcpp_result_gen;
END_RCPP
}
// getTreatmentsSubgroups
List getTreatmentsSubgroups(int maxNumberOfSubjects, IntegerVector allocationFraction, CharacterVector subGroups, NumericVector prevalences);
RcppExport SEXP _rpact_getTreatmentsSubgroups(SEXP maxNumberOfSubjectsSEXP, SEXP allocationFractionSEXP, SEXP subGroupsSEXP, SEXP prevalencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type maxNumberOfSubjects(maxNumberOfSubjectsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type allocationFraction(allocationFractionSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type subGroups(subGroupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prevalences(prevalencesSEXP);
    rcpp_result_gen = Rcpp::wrap(getTreatmentsSubgroups(maxNumberOfSubjects, allocationFraction, subGroups, prevalences));
    return rcpp_result_gen;
END_RCPP
}
// updateSubGroupVector
CharacterVector updateSubGroupVector(int k, int maxNumberOfSubjects, IntegerVector numberOfSubjects, const CharacterVector& subGroupVector, CharacterVector subGroups, NumericVector prevSelected);
RcppExport SEXP _rpact_updateSubGroupVector(SEXP kSEXP, SEXP maxNumberOfSubjectsSEXP, SEXP numberOfSubjectsSEXP, SEXP subGroupVectorSEXP, SEXP subGroupsSEXP, SEXP prevSelectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfSubjects(maxNumberOfSubjectsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type numberOfSubjects(numberOfSubjectsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type subGroupVector(subGroupVectorSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type subGroups(subGroupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prevSelected(prevSelectedSEXP);
    rcpp_result_gen = Rcpp::wrap(updateSubGroupVector(k, maxNumberOfSubjects, numberOfSubjects, subGroupVector, subGroups, prevSelected));
    return rcpp_result_gen;
END_RCPP
}
// getSimulatedStageResultsSurvivalEnrichmentSubjectsBased
List getSimulatedStageResultsSurvivalEnrichmentSubjectsBased(Environment design, NumericVector weights, CharacterVector subGroups, NumericVector prevalences, NumericVector piControls, double kappa, NumericVector phi, double eventTime, NumericVector hazardRatios, bool directionUpper, bool stratifiedAnalysis, NumericVector plannedEvents, NumericVector recruitmentTimes, IntegerVector allocationFraction, std::string typeOfSelection, std::string effectMeasure, LogicalVector adaptations, double epsilonValue, double rValue, double threshold, NumericVector minNumberOfEventsPerStage, NumericVector maxNumberOfEventsPerStage, double conditionalPower, double thetaH1, Nullable<Function> calcEventsFunction, bool calcEventsFunctionIsUserDefined, Nullable<Function> selectPopulationsFunction);
RcppExport SEXP _rpact_getSimulatedStageResultsSurvivalEnrichmentSubjectsBased(SEXP designSEXP, SEXP weightsSEXP, SEXP subGroupsSEXP, SEXP prevalencesSEXP, SEXP piControlsSEXP, SEXP kappaSEXP, SEXP phiSEXP, SEXP eventTimeSEXP, SEXP hazardRatiosSEXP, SEXP directionUpperSEXP, SEXP stratifiedAnalysisSEXP, SEXP plannedEventsSEXP, SEXP recruitmentTimesSEXP, SEXP allocationFractionSEXP, SEXP typeOfSelectionSEXP, SEXP effectMeasureSEXP, SEXP adaptationsSEXP, SEXP epsilonValueSEXP, SEXP rValueSEXP, SEXP thresholdSEXP, SEXP minNumberOfEventsPerStageSEXP, SEXP maxNumberOfEventsPerStageSEXP, SEXP conditionalPowerSEXP, SEXP thetaH1SEXP, SEXP calcEventsFunctionSEXP, SEXP calcEventsFunctionIsUserDefinedSEXP, SEXP selectPopulationsFunctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type design(designSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type subGroups(subGroupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prevalences(prevalencesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piControls(piControlsSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type eventTime(eventTimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hazardRatios(hazardRatiosSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< bool >::type stratifiedAnalysis(stratifiedAnalysisSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedEvents(plannedEventsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type recruitmentTimes(recruitmentTimesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type allocationFraction(allocationFractionSEXP);
    Rcpp::traits::input_parameter< std::string >::type typeOfSelection(typeOfSelectionSEXP);
    Rcpp::traits::input_parameter< std::string >::type effectMeasure(effectMeasureSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type adaptations(adaptationsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilonValue(epsilonValueSEXP);
    Rcpp::traits::input_parameter< double >::type rValue(rValueSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfEventsPerStage(minNumberOfEventsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfEventsPerStage(maxNumberOfEventsPerStageSEXP);
    Rcpp::traits::input_parameter< double >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH1(thetaH1SEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type calcEventsFunction(calcEventsFunctionSEXP);
    Rcpp::traits::input_parameter< bool >::type calcEventsFunctionIsUserDefined(calcEventsFunctionIsUserDefinedSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type selectPopulationsFunction(selectPopulationsFunctionSEXP);
    rcpp_result_gen = Rcpp::wrap(getSimulatedStageResultsSurvivalEnrichmentSubjectsBased(design, weights, subGroups, prevalences, piControls, kappa, phi, eventTime, hazardRatios, directionUpper, stratifiedAnalysis, plannedEvents, recruitmentTimes, allocationFraction, typeOfSelection, effectMeasure, adaptations, epsilonValue, rValue, threshold, minNumberOfEventsPerStage, maxNumberOfEventsPerStage, conditionalPower, thetaH1, calcEventsFunction, calcEventsFunctionIsUserDefined, selectPopulationsFunction));
    return rcpp_result_gen;
END_RCPP
}
// performSimulationEnrichmentSurvivalLoop
List performSimulationEnrichmentSurvivalLoop(int cols, int maxNumberOfIterations, Environment design, NumericVector weights, List effectList, double kappa, NumericVector phi, double eventTime, NumericVector recruitmentTimes, IntegerVector allocationFraction, bool directionUpper, bool stratifiedAnalysis, NumericVector plannedEvents, std::string typeOfSelection, std::string effectMeasure, LogicalVector adaptations, double epsilonValue, double rValue, double threshold, NumericVector minNumberOfEventsPerStage, NumericVector maxNumberOfEventsPerStage, double conditionalPower, double thetaH1, Nullable<Function> calcEventsFunction, bool calcEventsFunctionIsUserDefined, Nullable<Function> selectPopulationsFunction, IntegerMatrix indices, std::string intersectionTest, std::string successCriterion, int gMax, int kMax);
RcppExport SEXP _rpact_performSimulationEnrichmentSurvivalLoop(SEXP colsSEXP, SEXP maxNumberOfIterationsSEXP, SEXP designSEXP, SEXP weightsSEXP, SEXP effectListSEXP, SEXP kappaSEXP, SEXP phiSEXP, SEXP eventTimeSEXP, SEXP recruitmentTimesSEXP, SEXP allocationFractionSEXP, SEXP directionUpperSEXP, SEXP stratifiedAnalysisSEXP, SEXP plannedEventsSEXP, SEXP typeOfSelectionSEXP, SEXP effectMeasureSEXP, SEXP adaptationsSEXP, SEXP epsilonValueSEXP, SEXP rValueSEXP, SEXP thresholdSEXP, SEXP minNumberOfEventsPerStageSEXP, SEXP maxNumberOfEventsPerStageSEXP, SEXP conditionalPowerSEXP, SEXP thetaH1SEXP, SEXP calcEventsFunctionSEXP, SEXP calcEventsFunctionIsUserDefinedSEXP, SEXP selectPopulationsFunctionSEXP, SEXP indicesSEXP, SEXP intersectionTestSEXP, SEXP successCriterionSEXP, SEXP gMaxSEXP, SEXP kMaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfIterations(maxNumberOfIterationsSEXP);
    Rcpp::traits::input_parameter< Environment >::type design(designSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< List >::type effectList(effectListSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type eventTime(eventTimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type recruitmentTimes(recruitmentTimesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type allocationFraction(allocationFractionSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< bool >::type stratifiedAnalysis(stratifiedAnalysisSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedEvents(plannedEventsSEXP);
    Rcpp::traits::input_parameter< std::string >::type typeOfSelection(typeOfSelectionSEXP);
    Rcpp::traits::input_parameter< std::string >::type effectMeasure(effectMeasureSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type adaptations(adaptationsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilonValue(epsilonValueSEXP);
    Rcpp::traits::input_parameter< double >::type rValue(rValueSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfEventsPerStage(minNumberOfEventsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfEventsPerStage(maxNumberOfEventsPerStageSEXP);
    Rcpp::traits::input_parameter< double >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH1(thetaH1SEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type calcEventsFunction(calcEventsFunctionSEXP);
    Rcpp::traits::input_parameter< bool >::type calcEventsFunctionIsUserDefined(calcEventsFunctionIsUserDefinedSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type selectPopulationsFunction(selectPopulationsFunctionSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< std::string >::type intersectionTest(intersectionTestSEXP);
    Rcpp::traits::input_parameter< std::string >::type successCriterion(successCriterionSEXP);
    Rcpp::traits::input_parameter< int >::type gMax(gMaxSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    rcpp_result_gen = Rcpp::wrap(performSimulationEnrichmentSurvivalLoop(cols, maxNumberOfIterations, design, weights, effectList, kappa, phi, eventTime, recruitmentTimes, allocationFraction, directionUpper, stratifiedAnalysis, plannedEvents, typeOfSelection, effectMeasure, adaptations, epsilonValue, rValue, threshold, minNumberOfEventsPerStage, maxNumberOfEventsPerStage, conditionalPower, thetaH1, calcEventsFunction, calcEventsFunctionIsUserDefined, selectPopulationsFunction, indices, intersectionTest, successCriterion, gMax, kMax));
    return rcpp_result_gen;
END_RCPP
}
// dunnettIntegrand1Int
double dunnettIntegrand1Int(double criticalValue, double informationAtInterim, NumericMatrix signedTestStatistics, NumericVector frac, LogicalVector indicesRow);
RcppExport SEXP _rpact_dunnettIntegrand1Int(SEXP criticalValueSEXP, SEXP informationAtInterimSEXP, SEXP signedTestStatisticsSEXP, SEXP fracSEXP, SEXP indicesRowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type criticalValue(criticalValueSEXP);
    Rcpp::traits::input_parameter< double >::type informationAtInterim(informationAtInterimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type signedTestStatistics(signedTestStatisticsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type frac(fracSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type indicesRow(indicesRowSEXP);
    rcpp_result_gen = Rcpp::wrap(dunnettIntegrand1Int(criticalValue, informationAtInterim, signedTestStatistics, frac, indicesRow));
    return rcpp_result_gen;
END_RCPP
}
// dunnettIntegrand1Evaluate
NumericVector dunnettIntegrand1Evaluate(NumericVector x, double criticalValue, double informationAtInterim, NumericMatrix signedTestStatistics, NumericVector frac, LogicalVector indicesRow);
RcppExport SEXP _rpact_dunnettIntegrand1Evaluate(SEXP xSEXP, SEXP criticalValueSEXP, SEXP informationAtInterimSEXP, SEXP signedTestStatisticsSEXP, SEXP fracSEXP, SEXP indicesRowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type criticalValue(criticalValueSEXP);
    Rcpp::traits::input_parameter< double >::type informationAtInterim(informationAtInterimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type signedTestStatistics(signedTestStatisticsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type frac(fracSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type indicesRow(indicesRowSEXP);
    rcpp_result_gen = Rcpp::wrap(dunnettIntegrand1Evaluate(x, criticalValue, informationAtInterim, signedTestStatistics, frac, indicesRow));
    return rcpp_result_gen;
END_RCPP
}
// dunnettIntegrand2Int
double dunnettIntegrand2Int(double maxOverallTestStatistic, double informationAtInterim, NumericMatrix signedTestStatistics, NumericVector frac, LogicalVector indicesRow, NumericMatrix overallTestStatistics);
RcppExport SEXP _rpact_dunnettIntegrand2Int(SEXP maxOverallTestStatisticSEXP, SEXP informationAtInterimSEXP, SEXP signedTestStatisticsSEXP, SEXP fracSEXP, SEXP indicesRowSEXP, SEXP overallTestStatisticsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type maxOverallTestStatistic(maxOverallTestStatisticSEXP);
    Rcpp::traits::input_parameter< double >::type informationAtInterim(informationAtInterimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type signedTestStatistics(signedTestStatisticsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type frac(fracSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type indicesRow(indicesRowSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type overallTestStatistics(overallTestStatisticsSEXP);
    rcpp_result_gen = Rcpp::wrap(dunnettIntegrand2Int(maxOverallTestStatistic, informationAtInterim, signedTestStatistics, frac, indicesRow, overallTestStatistics));
    return rcpp_result_gen;
END_RCPP
}
// dunnettIntegrand2Evaluate
NumericVector dunnettIntegrand2Evaluate(NumericVector x, double maxOverallTestStatistic, double informationAtInterim, NumericMatrix signedTestStatistics, NumericVector frac, LogicalVector indicesRow, NumericMatrix overallTestStatistics);
RcppExport SEXP _rpact_dunnettIntegrand2Evaluate(SEXP xSEXP, SEXP maxOverallTestStatisticSEXP, SEXP informationAtInterimSEXP, SEXP signedTestStatisticsSEXP, SEXP fracSEXP, SEXP indicesRowSEXP, SEXP overallTestStatisticsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type maxOverallTestStatistic(maxOverallTestStatisticSEXP);
    Rcpp::traits::input_parameter< double >::type informationAtInterim(informationAtInterimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type signedTestStatistics(signedTestStatisticsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type frac(fracSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type indicesRow(indicesRowSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type overallTestStatistics(overallTestStatisticsSEXP);
    rcpp_result_gen = Rcpp::wrap(dunnettIntegrand2Evaluate(x, maxOverallTestStatistic, informationAtInterim, signedTestStatistics, frac, indicesRow, overallTestStatistics));
    return rcpp_result_gen;
END_RCPP
}
// dunnettIntegrand3Int
double dunnettIntegrand3Int(double maxTestStatistic, NumericVector frac, LogicalVector indicesRow, NumericMatrix separatePValues);
RcppExport SEXP _rpact_dunnettIntegrand3Int(SEXP maxTestStatisticSEXP, SEXP fracSEXP, SEXP indicesRowSEXP, SEXP separatePValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type maxTestStatistic(maxTestStatisticSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type frac(fracSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type indicesRow(indicesRowSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type separatePValues(separatePValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(dunnettIntegrand3Int(maxTestStatistic, frac, indicesRow, separatePValues));
    return rcpp_result_gen;
END_RCPP
}
// dunnettIntegrand3Evaluate
NumericVector dunnettIntegrand3Evaluate(NumericVector x, double maxTestStatistic, NumericVector frac, LogicalVector indicesRow, NumericMatrix separatePValues);
RcppExport SEXP _rpact_dunnettIntegrand3Evaluate(SEXP xSEXP, SEXP maxTestStatisticSEXP, SEXP fracSEXP, SEXP indicesRowSEXP, SEXP separatePValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type maxTestStatistic(maxTestStatisticSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type frac(fracSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type indicesRow(indicesRowSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type separatePValues(separatePValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(dunnettIntegrand3Evaluate(x, maxTestStatistic, frac, indicesRow, separatePValues));
    return rcpp_result_gen;
END_RCPP
}
// performClosedConditionalDunnettTestForSimulation
List performClosedConditionalDunnettTestForSimulation(List stageResults, Environment design, LogicalMatrix indices, NumericVector criticalValuesDunnett, std::string successCriterion);
RcppExport SEXP _rpact_performClosedConditionalDunnettTestForSimulation(SEXP stageResultsSEXP, SEXP designSEXP, SEXP indicesSEXP, SEXP criticalValuesDunnettSEXP, SEXP successCriterionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type stageResults(stageResultsSEXP);
    Rcpp::traits::input_parameter< Environment >::type design(designSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type criticalValuesDunnett(criticalValuesDunnettSEXP);
    Rcpp::traits::input_parameter< std::string >::type successCriterion(successCriterionSEXP);
    rcpp_result_gen = Rcpp::wrap(performClosedConditionalDunnettTestForSimulation(stageResults, design, indices, criticalValuesDunnett, successCriterion));
    return rcpp_result_gen;
END_RCPP
}
// performClosedCombinationTestForSimulationMultiArm
List performClosedCombinationTestForSimulationMultiArm(List stageResults, Environment design, LogicalMatrix indices, std::string intersectionTest, std::string successCriterion);
RcppExport SEXP _rpact_performClosedCombinationTestForSimulationMultiArm(SEXP stageResultsSEXP, SEXP designSEXP, SEXP indicesSEXP, SEXP intersectionTestSEXP, SEXP successCriterionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type stageResults(stageResultsSEXP);
    Rcpp::traits::input_parameter< Environment >::type design(designSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< std::string >::type intersectionTest(intersectionTestSEXP);
    Rcpp::traits::input_parameter< std::string >::type successCriterion(successCriterionSEXP);
    rcpp_result_gen = Rcpp::wrap(performClosedCombinationTestForSimulationMultiArm(stageResults, design, indices, intersectionTest, successCriterion));
    return rcpp_result_gen;
END_RCPP
}
// getSimulatedStageMeansMultiArmCpp
List getSimulatedStageMeansMultiArmCpp(Environment design, NumericVector muVector, double stDev, NumericVector plannedSubjects, std::string typeOfSelection, std::string effectMeasure, LogicalVector adaptations, double epsilonValue, double rValue, double threshold, NumericVector allocationRatioPlanned, NumericVector minNumberOfSubjectsPerStage, NumericVector maxNumberOfSubjectsPerStage, double conditionalPower, double thetaH1, double stDevH1, Function calcSubjectsFunction, bool calcSubjectsFunctionIsUserDefined, Nullable<Function> selectArmsFunction);
RcppExport SEXP _rpact_getSimulatedStageMeansMultiArmCpp(SEXP designSEXP, SEXP muVectorSEXP, SEXP stDevSEXP, SEXP plannedSubjectsSEXP, SEXP typeOfSelectionSEXP, SEXP effectMeasureSEXP, SEXP adaptationsSEXP, SEXP epsilonValueSEXP, SEXP rValueSEXP, SEXP thresholdSEXP, SEXP allocationRatioPlannedSEXP, SEXP minNumberOfSubjectsPerStageSEXP, SEXP maxNumberOfSubjectsPerStageSEXP, SEXP conditionalPowerSEXP, SEXP thetaH1SEXP, SEXP stDevH1SEXP, SEXP calcSubjectsFunctionSEXP, SEXP calcSubjectsFunctionIsUserDefinedSEXP, SEXP selectArmsFunctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type design(designSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type muVector(muVectorSEXP);
    Rcpp::traits::input_parameter< double >::type stDev(stDevSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedSubjects(plannedSubjectsSEXP);
    Rcpp::traits::input_parameter< std::string >::type typeOfSelection(typeOfSelectionSEXP);
    Rcpp::traits::input_parameter< std::string >::type effectMeasure(effectMeasureSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type adaptations(adaptationsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilonValue(epsilonValueSEXP);
    Rcpp::traits::input_parameter< double >::type rValue(rValueSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type allocationRatioPlanned(allocationRatioPlannedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfSubjectsPerStage(minNumberOfSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfSubjectsPerStage(maxNumberOfSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< double >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH1(thetaH1SEXP);
    Rcpp::traits::input_parameter< double >::type stDevH1(stDevH1SEXP);
    Rcpp::traits::input_parameter< Function >::type calcSubjectsFunction(calcSubjectsFunctionSEXP);
    Rcpp::traits::input_parameter< bool >::type calcSubjectsFunctionIsUserDefined(calcSubjectsFunctionIsUserDefinedSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type selectArmsFunction(selectArmsFunctionSEXP);
    rcpp_result_gen = Rcpp::wrap(getSimulatedStageMeansMultiArmCpp(design, muVector, stDev, plannedSubjects, typeOfSelection, effectMeasure, adaptations, epsilonValue, rValue, threshold, allocationRatioPlanned, minNumberOfSubjectsPerStage, maxNumberOfSubjectsPerStage, conditionalPower, thetaH1, stDevH1, calcSubjectsFunction, calcSubjectsFunctionIsUserDefined, selectArmsFunction));
    return rcpp_result_gen;
END_RCPP
}
// simulationMultiArmMeansInnerLoopCpp
List simulationMultiArmMeansInnerLoopCpp(NumericMatrix iterations, NumericMatrix simulatedFutilityStopping, NumericMatrix simulatedConditionalPower, int i, int j, int gMax, int kMax, int cols, int index, NumericVector simulatedSubjectsPerStage, NumericVector simulatedRejections, NumericVector simulatedSelections, NumericMatrix simulatedNumberOfActiveArms, NumericMatrix simulatedSuccessStopping, NumericVector muMaxVector, NumericMatrix effectMatrix, NumericVector dataIterationNumber, NumericVector dataStageNumber, NumericVector dataArmNumber, NumericVector dataAlternative, NumericVector dataEffect, NumericVector dataSubjectsControlArm, NumericVector dataSubjectsActiveArm, NumericVector dataNumberOfSubjects, NumericVector dataNumberOfCumulatedSubjects, NumericVector dataRejectPerStage, NumericVector dataTestStatistics, NumericVector dataSuccessStop, LogicalVector dataFutilityStop, NumericVector dataConditionalCriticalValue, NumericVector dataConditionalPowerAchieved, NumericVector dataEffectEstimate, NumericVector dataPValuesSeparate, NumericVector simulatedRejectAtLeastOne, Environment design, NumericMatrix indices, Nullable<NumericVector> criticalValuesDunnett, std::string intersectionTest, std::string successCriterion, double stDev, NumericVector plannedSubjects, std::string typeOfSelection, std::string effectMeasure, LogicalVector adaptations, double epsilonValue, double rValue, double threshold, NumericVector allocationRatioPlanned, NumericVector minNumberOfSubjectsPerStage, NumericVector maxNumberOfSubjectsPerStage, double conditionalPower, double thetaH1, double stDevH1, Function calcSubjectsFunction, bool calcSubjectsFunctionIsUserDefined, Nullable<Function> selectArmsFunction, List stageResults);
RcppExport SEXP _rpact_simulationMultiArmMeansInnerLoopCpp(SEXP iterationsSEXP, SEXP simulatedFutilityStoppingSEXP, SEXP simulatedConditionalPowerSEXP, SEXP iSEXP, SEXP jSEXP, SEXP gMaxSEXP, SEXP kMaxSEXP, SEXP colsSEXP, SEXP indexSEXP, SEXP simulatedSubjectsPerStageSEXP, SEXP simulatedRejectionsSEXP, SEXP simulatedSelectionsSEXP, SEXP simulatedNumberOfActiveArmsSEXP, SEXP simulatedSuccessStoppingSEXP, SEXP muMaxVectorSEXP, SEXP effectMatrixSEXP, SEXP dataIterationNumberSEXP, SEXP dataStageNumberSEXP, SEXP dataArmNumberSEXP, SEXP dataAlternativeSEXP, SEXP dataEffectSEXP, SEXP dataSubjectsControlArmSEXP, SEXP dataSubjectsActiveArmSEXP, SEXP dataNumberOfSubjectsSEXP, SEXP dataNumberOfCumulatedSubjectsSEXP, SEXP dataRejectPerStageSEXP, SEXP dataTestStatisticsSEXP, SEXP dataSuccessStopSEXP, SEXP dataFutilityStopSEXP, SEXP dataConditionalCriticalValueSEXP, SEXP dataConditionalPowerAchievedSEXP, SEXP dataEffectEstimateSEXP, SEXP dataPValuesSeparateSEXP, SEXP simulatedRejectAtLeastOneSEXP, SEXP designSEXP, SEXP indicesSEXP, SEXP criticalValuesDunnettSEXP, SEXP intersectionTestSEXP, SEXP successCriterionSEXP, SEXP stDevSEXP, SEXP plannedSubjectsSEXP, SEXP typeOfSelectionSEXP, SEXP effectMeasureSEXP, SEXP adaptationsSEXP, SEXP epsilonValueSEXP, SEXP rValueSEXP, SEXP thresholdSEXP, SEXP allocationRatioPlannedSEXP, SEXP minNumberOfSubjectsPerStageSEXP, SEXP maxNumberOfSubjectsPerStageSEXP, SEXP conditionalPowerSEXP, SEXP thetaH1SEXP, SEXP stDevH1SEXP, SEXP calcSubjectsFunctionSEXP, SEXP calcSubjectsFunctionIsUserDefinedSEXP, SEXP selectArmsFunctionSEXP, SEXP stageResultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type simulatedFutilityStopping(simulatedFutilityStoppingSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type simulatedConditionalPower(simulatedConditionalPowerSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type gMax(gMaxSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type simulatedSubjectsPerStage(simulatedSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type simulatedRejections(simulatedRejectionsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type simulatedSelections(simulatedSelectionsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type simulatedNumberOfActiveArms(simulatedNumberOfActiveArmsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type simulatedSuccessStopping(simulatedSuccessStoppingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type muMaxVector(muMaxVectorSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type effectMatrix(effectMatrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataIterationNumber(dataIterationNumberSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataStageNumber(dataStageNumberSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataArmNumber(dataArmNumberSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataAlternative(dataAlternativeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataEffect(dataEffectSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataSubjectsControlArm(dataSubjectsControlArmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataSubjectsActiveArm(dataSubjectsActiveArmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataNumberOfSubjects(dataNumberOfSubjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataNumberOfCumulatedSubjects(dataNumberOfCumulatedSubjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataRejectPerStage(dataRejectPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataTestStatistics(dataTestStatisticsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataSuccessStop(dataSuccessStopSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type dataFutilityStop(dataFutilityStopSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataConditionalCriticalValue(dataConditionalCriticalValueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataConditionalPowerAchieved(dataConditionalPowerAchievedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataEffectEstimate(dataEffectEstimateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dataPValuesSeparate(dataPValuesSeparateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type simulatedRejectAtLeastOne(simulatedRejectAtLeastOneSEXP);
    Rcpp::traits::input_parameter< Environment >::type design(designSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type criticalValuesDunnett(criticalValuesDunnettSEXP);
    Rcpp::traits::input_parameter< std::string >::type intersectionTest(intersectionTestSEXP);
    Rcpp::traits::input_parameter< std::string >::type successCriterion(successCriterionSEXP);
    Rcpp::traits::input_parameter< double >::type stDev(stDevSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedSubjects(plannedSubjectsSEXP);
    Rcpp::traits::input_parameter< std::string >::type typeOfSelection(typeOfSelectionSEXP);
    Rcpp::traits::input_parameter< std::string >::type effectMeasure(effectMeasureSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type adaptations(adaptationsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilonValue(epsilonValueSEXP);
    Rcpp::traits::input_parameter< double >::type rValue(rValueSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type allocationRatioPlanned(allocationRatioPlannedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfSubjectsPerStage(minNumberOfSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfSubjectsPerStage(maxNumberOfSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< double >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH1(thetaH1SEXP);
    Rcpp::traits::input_parameter< double >::type stDevH1(stDevH1SEXP);
    Rcpp::traits::input_parameter< Function >::type calcSubjectsFunction(calcSubjectsFunctionSEXP);
    Rcpp::traits::input_parameter< bool >::type calcSubjectsFunctionIsUserDefined(calcSubjectsFunctionIsUserDefinedSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type selectArmsFunction(selectArmsFunctionSEXP);
    Rcpp::traits::input_parameter< List >::type stageResults(stageResultsSEXP);
    rcpp_result_gen = Rcpp::wrap(simulationMultiArmMeansInnerLoopCpp(iterations, simulatedFutilityStopping, simulatedConditionalPower, i, j, gMax, kMax, cols, index, simulatedSubjectsPerStage, simulatedRejections, simulatedSelections, simulatedNumberOfActiveArms, simulatedSuccessStopping, muMaxVector, effectMatrix, dataIterationNumber, dataStageNumber, dataArmNumber, dataAlternative, dataEffect, dataSubjectsControlArm, dataSubjectsActiveArm, dataNumberOfSubjects, dataNumberOfCumulatedSubjects, dataRejectPerStage, dataTestStatistics, dataSuccessStop, dataFutilityStop, dataConditionalCriticalValue, dataConditionalPowerAchieved, dataEffectEstimate, dataPValuesSeparate, simulatedRejectAtLeastOne, design, indices, criticalValuesDunnett, intersectionTest, successCriterion, stDev, plannedSubjects, typeOfSelection, effectMeasure, adaptations, epsilonValue, rValue, threshold, allocationRatioPlanned, minNumberOfSubjectsPerStage, maxNumberOfSubjectsPerStage, conditionalPower, thetaH1, stDevH1, calcSubjectsFunction, calcSubjectsFunctionIsUserDefined, selectArmsFunction, stageResults));
    return rcpp_result_gen;
END_RCPP
}
// hmm
NumericVector hmm(int gMax, int k, int i, int cols, int kMax, NumericVector simulatedRejections, List closedTest, LogicalVector rejectedArmsBefore, LogicalMatrix cheat);
RcppExport SEXP _rpact_hmm(SEXP gMaxSEXP, SEXP kSEXP, SEXP iSEXP, SEXP colsSEXP, SEXP kMaxSEXP, SEXP simulatedRejectionsSEXP, SEXP closedTestSEXP, SEXP rejectedArmsBeforeSEXP, SEXP cheatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type gMax(gMaxSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type simulatedRejections(simulatedRejectionsSEXP);
    Rcpp::traits::input_parameter< List >::type closedTest(closedTestSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type rejectedArmsBefore(rejectedArmsBeforeSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type cheat(cheatSEXP);
    rcpp_result_gen = Rcpp::wrap(hmm(gMax, k, i, cols, kMax, simulatedRejections, closedTest, rejectedArmsBefore, cheat));
    return rcpp_result_gen;
END_RCPP
}
// first
NumericVector first(int gMax, int k, int i, int cols, int kMax, NumericVector simulatedSelections, List closedTest);
RcppExport SEXP _rpact_first(SEXP gMaxSEXP, SEXP kSEXP, SEXP iSEXP, SEXP colsSEXP, SEXP kMaxSEXP, SEXP simulatedSelectionsSEXP, SEXP closedTestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type gMax(gMaxSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type simulatedSelections(simulatedSelectionsSEXP);
    Rcpp::traits::input_parameter< List >::type closedTest(closedTestSEXP);
    rcpp_result_gen = Rcpp::wrap(first(gMax, k, i, cols, kMax, simulatedSelections, closedTest));
    return rcpp_result_gen;
END_RCPP
}
// funnyBool
bool funnyBool(int k, int kMax, List closedTest);
RcppExport SEXP _rpact_funnyBool(SEXP kSEXP, SEXP kMaxSEXP, SEXP closedTestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< List >::type closedTest(closedTestSEXP);
    rcpp_result_gen = Rcpp::wrap(funnyBool(k, kMax, closedTest));
    return rcpp_result_gen;
END_RCPP
}
// lastSection
List lastSection(NumericVector simulatedSubjectsPerStage, NumericMatrix iterations, int i, int gMax, int kMax, int cols, NumericVector simulatedRejections, NumericMatrix simulatedSuccessStopping, NumericMatrix simulatedFutilityStopping, int maxNumberOfIterations, NumericVector expectedNumberOfSubjects);
RcppExport SEXP _rpact_lastSection(SEXP simulatedSubjectsPerStageSEXP, SEXP iterationsSEXP, SEXP iSEXP, SEXP gMaxSEXP, SEXP kMaxSEXP, SEXP colsSEXP, SEXP simulatedRejectionsSEXP, SEXP simulatedSuccessStoppingSEXP, SEXP simulatedFutilityStoppingSEXP, SEXP maxNumberOfIterationsSEXP, SEXP expectedNumberOfSubjectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type simulatedSubjectsPerStage(simulatedSubjectsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type gMax(gMaxSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type simulatedRejections(simulatedRejectionsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type simulatedSuccessStopping(simulatedSuccessStoppingSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type simulatedFutilityStopping(simulatedFutilityStoppingSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfIterations(maxNumberOfIterationsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type expectedNumberOfSubjects(expectedNumberOfSubjectsSEXP);
    rcpp_result_gen = Rcpp::wrap(lastSection(simulatedSubjectsPerStage, iterations, i, gMax, kMax, cols, simulatedRejections, simulatedSuccessStopping, simulatedFutilityStopping, maxNumberOfIterations, expectedNumberOfSubjects));
    return rcpp_result_gen;
END_RCPP
}
// getSimulationSurvivalMultiArmStageEvents
double getSimulationSurvivalMultiArmStageEvents(int stage, bool directionUpper, double conditionalPower, NumericVector conditionalCriticalValue, NumericVector plannedEvents, NumericVector allocationRatioPlanned, LogicalMatrix selectedArms, double thetaH1, NumericMatrix overallEffects, NumericVector minNumberOfEventsPerStage, NumericVector maxNumberOfEventsPerStage);
RcppExport SEXP _rpact_getSimulationSurvivalMultiArmStageEvents(SEXP stageSEXP, SEXP directionUpperSEXP, SEXP conditionalPowerSEXP, SEXP conditionalCriticalValueSEXP, SEXP plannedEventsSEXP, SEXP allocationRatioPlannedSEXP, SEXP selectedArmsSEXP, SEXP thetaH1SEXP, SEXP overallEffectsSEXP, SEXP minNumberOfEventsPerStageSEXP, SEXP maxNumberOfEventsPerStageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type stage(stageSEXP);
    Rcpp::traits::input_parameter< bool >::type directionUpper(directionUpperSEXP);
    Rcpp::traits::input_parameter< double >::type conditionalPower(conditionalPowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type conditionalCriticalValue(conditionalCriticalValueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plannedEvents(plannedEventsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type allocationRatioPlanned(allocationRatioPlannedSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type selectedArms(selectedArmsSEXP);
    Rcpp::traits::input_parameter< double >::type thetaH1(thetaH1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type overallEffects(overallEffectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minNumberOfEventsPerStage(minNumberOfEventsPerStageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxNumberOfEventsPerStage(maxNumberOfEventsPerStageSEXP);
    rcpp_result_gen = Rcpp::wrap(getSimulationSurvivalMultiArmStageEvents(stage, directionUpper, conditionalPower, conditionalCriticalValue, plannedEvents, allocationRatioPlanned, selectedArms, thetaH1, overallEffects, minNumberOfEventsPerStage, maxNumberOfEventsPerStage));
    return rcpp_result_gen;
END_RCPP
}
// findObservationTime
double findObservationTime(NumericVector accrualTime, NumericVector survivalTime, NumericVector dropoutTime, double requiredStageEvents);
RcppExport SEXP _rpact_findObservationTime(SEXP accrualTimeSEXP, SEXP survivalTimeSEXP, SEXP dropoutTimeSEXP, SEXP requiredStageEventsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type accrualTime(accrualTimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type survivalTime(survivalTimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dropoutTime(dropoutTimeSEXP);
    Rcpp::traits::input_parameter< double >::type requiredStageEvents(requiredStageEventsSEXP);
    rcpp_result_gen = Rcpp::wrap(findObservationTime(accrualTime, survivalTime, dropoutTime, requiredStageEvents));
    return rcpp_result_gen;
END_RCPP
}
// getOneMinusQNorm
double getOneMinusQNorm(double p, double mean, double sd, double lowerTail, double logP, double epsilon);
RcppExport SEXP _rpact_getOneMinusQNorm(SEXP pSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP lowerTailSEXP, SEXP logPSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lowerTail(lowerTailSEXP);
    Rcpp::traits::input_parameter< double >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(getOneMinusQNorm(p, mean, sd, lowerTail, logP, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// order
IntegerVector order(NumericVector x);
RcppExport SEXP _rpact_order(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(order(x));
    return rcpp_result_gen;
END_RCPP
}
// zeroin
double zeroin(Function f, double lower, double upper, double tolerance, int maxIter);
RcppExport SEXP _rpact_zeroin(SEXP fSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP toleranceSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(zeroin(f, lower, upper, tolerance, maxIter));
    return rcpp_result_gen;
END_RCPP
}
// getCipheredValue
std::string getCipheredValue(String x);
RcppExport SEXP _rpact_getCipheredValue(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(getCipheredValue(x));
    return rcpp_result_gen;
END_RCPP
}
// getFraction
IntegerVector getFraction(double x, double epsilon, int maxNumberOfSearchSteps);
RcppExport SEXP _rpact_getFraction(SEXP xSEXP, SEXP epsilonSEXP, SEXP maxNumberOfSearchStepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfSearchSteps(maxNumberOfSearchStepsSEXP);
    rcpp_result_gen = Rcpp::wrap(getFraction(x, epsilon, maxNumberOfSearchSteps));
    return rcpp_result_gen;
END_RCPP
}
// getFractions
List getFractions(NumericVector x, double epsilon, int maxNumberOfSearchSteps);
RcppExport SEXP _rpact_getFractions(SEXP xSEXP, SEXP epsilonSEXP, SEXP maxNumberOfSearchStepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type maxNumberOfSearchSteps(maxNumberOfSearchStepsSEXP);
    rcpp_result_gen = Rcpp::wrap(getFractions(x, epsilon, maxNumberOfSearchSteps));
    return rcpp_result_gen;
END_RCPP
}
// getMultivarNormalDistribution
double getMultivarNormalDistribution(NumericVector upper, NumericMatrix sigma);
RcppExport SEXP _rpact_getMultivarNormalDistribution(SEXP upperSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(getMultivarNormalDistribution(upper, sigma));
    return rcpp_result_gen;
END_RCPP
}
// tcrossprod
NumericMatrix tcrossprod(NumericVector x);
RcppExport SEXP _rpact_tcrossprod(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(tcrossprod(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rpact_mvnprd", (DL_FUNC) &_rpact_mvnprd, 7},
    {"_rpact_mvstud", (DL_FUNC) &_rpact_mvstud, 9},
    {"_rpact_as251Normal", (DL_FUNC) &_rpact_as251Normal, 6},
    {"_rpact_estimate_nb", (DL_FUNC) &_rpact_estimate_nb, 4},
    {"_rpact_getFisherCombinationSizeCpp", (DL_FUNC) &_rpact_getFisherCombinationSizeCpp, 5},
    {"_rpact_getSimulatedAlphaCpp", (DL_FUNC) &_rpact_getSimulatedAlphaCpp, 5},
    {"_rpact_getFisherCombinationCasesCpp", (DL_FUNC) &_rpact_getFisherCombinationCasesCpp, 2},
    {"_rpact_getDesignFisherTryCpp", (DL_FUNC) &_rpact_getDesignFisherTryCpp, 8},
    {"_rpact_getGroupSequentialProbabilitiesCpp", (DL_FUNC) &_rpact_getGroupSequentialProbabilitiesCpp, 2},
    {"_rpact_getDesignGroupSequentialPampallonaTsiatisCpp", (DL_FUNC) &_rpact_getDesignGroupSequentialPampallonaTsiatisCpp, 9},
    {"_rpact_getDesignGroupSequentialUserDefinedAlphaSpendingCpp", (DL_FUNC) &_rpact_getDesignGroupSequentialUserDefinedAlphaSpendingCpp, 7},
    {"_rpact_getDesignGroupSequentialAlphaSpendingCpp", (DL_FUNC) &_rpact_getDesignGroupSequentialAlphaSpendingCpp, 9},
    {"_rpact_getDesignGroupSequentialDeltaWTCpp", (DL_FUNC) &_rpact_getDesignGroupSequentialDeltaWTCpp, 8},
    {"_rpact_getDesignGroupSequentialPocockCpp", (DL_FUNC) &_rpact_getDesignGroupSequentialPocockCpp, 7},
    {"_rpact_getDesignGroupSequentialOBrienAndFlemingCpp", (DL_FUNC) &_rpact_getDesignGroupSequentialOBrienAndFlemingCpp, 7},
    {"_rpact_getDesignGroupSequentialBetaSpendingCpp", (DL_FUNC) &_rpact_getDesignGroupSequentialBetaSpendingCpp, 16},
    {"_rpact_getDesignGroupSequentialUserDefinedBetaSpendingCpp", (DL_FUNC) &_rpact_getDesignGroupSequentialUserDefinedBetaSpendingCpp, 13},
    {"_rpact_getSimulationMeansLoopCpp", (DL_FUNC) &_rpact_getSimulationMeansLoopCpp, 24},
    {"_rpact_getSimulationRatesCpp", (DL_FUNC) &_rpact_getSimulationRatesCpp, 24},
    {"_rpact_logRankTest", (DL_FUNC) &_rpact_logRankTest, 8},
    {"_rpact_getSimulationSurvivalCpp", (DL_FUNC) &_rpact_getSimulationSurvivalCpp, 33},
    {"_rpact_selectPopulations", (DL_FUNC) &_rpact_selectPopulations, 5},
    {"_rpact_performClosedCombinationTestForSimulationEnrichment", (DL_FUNC) &_rpact_performClosedCombinationTestForSimulationEnrichment, 5},
    {"_rpact_createSelectedSubsets", (DL_FUNC) &_rpact_createSelectedSubsets, 1},
    {"_rpact_createSubGroups", (DL_FUNC) &_rpact_createSubGroups, 1},
    {"_rpact_createSubGroupsFromPopulation", (DL_FUNC) &_rpact_createSubGroupsFromPopulation, 2},
    {"_rpact_logRankTestEnrichment", (DL_FUNC) &_rpact_logRankTestEnrichment, 7},
    {"_rpact_getSimulationSurvivalEnrichmentStageEvents", (DL_FUNC) &_rpact_getSimulationSurvivalEnrichmentStageEvents, 11},
    {"_rpact_getTreatmentsSubgroups", (DL_FUNC) &_rpact_getTreatmentsSubgroups, 4},
    {"_rpact_updateSubGroupVector", (DL_FUNC) &_rpact_updateSubGroupVector, 6},
    {"_rpact_getSimulatedStageResultsSurvivalEnrichmentSubjectsBased", (DL_FUNC) &_rpact_getSimulatedStageResultsSurvivalEnrichmentSubjectsBased, 27},
    {"_rpact_performSimulationEnrichmentSurvivalLoop", (DL_FUNC) &_rpact_performSimulationEnrichmentSurvivalLoop, 31},
    {"_rpact_dunnettIntegrand1Int", (DL_FUNC) &_rpact_dunnettIntegrand1Int, 5},
    {"_rpact_dunnettIntegrand1Evaluate", (DL_FUNC) &_rpact_dunnettIntegrand1Evaluate, 6},
    {"_rpact_dunnettIntegrand2Int", (DL_FUNC) &_rpact_dunnettIntegrand2Int, 6},
    {"_rpact_dunnettIntegrand2Evaluate", (DL_FUNC) &_rpact_dunnettIntegrand2Evaluate, 7},
    {"_rpact_dunnettIntegrand3Int", (DL_FUNC) &_rpact_dunnettIntegrand3Int, 4},
    {"_rpact_dunnettIntegrand3Evaluate", (DL_FUNC) &_rpact_dunnettIntegrand3Evaluate, 5},
    {"_rpact_performClosedConditionalDunnettTestForSimulation", (DL_FUNC) &_rpact_performClosedConditionalDunnettTestForSimulation, 5},
    {"_rpact_performClosedCombinationTestForSimulationMultiArm", (DL_FUNC) &_rpact_performClosedCombinationTestForSimulationMultiArm, 5},
    {"_rpact_getSimulatedStageMeansMultiArmCpp", (DL_FUNC) &_rpact_getSimulatedStageMeansMultiArmCpp, 19},
    {"_rpact_simulationMultiArmMeansInnerLoopCpp", (DL_FUNC) &_rpact_simulationMultiArmMeansInnerLoopCpp, 57},
    {"_rpact_hmm", (DL_FUNC) &_rpact_hmm, 9},
    {"_rpact_first", (DL_FUNC) &_rpact_first, 7},
    {"_rpact_funnyBool", (DL_FUNC) &_rpact_funnyBool, 3},
    {"_rpact_lastSection", (DL_FUNC) &_rpact_lastSection, 11},
    {"_rpact_getSimulationSurvivalMultiArmStageEvents", (DL_FUNC) &_rpact_getSimulationSurvivalMultiArmStageEvents, 11},
    {"_rpact_findObservationTime", (DL_FUNC) &_rpact_findObservationTime, 4},
    {"_rpact_getOneMinusQNorm", (DL_FUNC) &_rpact_getOneMinusQNorm, 6},
    {"_rpact_order", (DL_FUNC) &_rpact_order, 1},
    {"_rpact_zeroin", (DL_FUNC) &_rpact_zeroin, 5},
    {"_rpact_getCipheredValue", (DL_FUNC) &_rpact_getCipheredValue, 1},
    {"_rpact_getFraction", (DL_FUNC) &_rpact_getFraction, 3},
    {"_rpact_getFractions", (DL_FUNC) &_rpact_getFractions, 3},
    {"_rpact_getMultivarNormalDistribution", (DL_FUNC) &_rpact_getMultivarNormalDistribution, 2},
    {"_rpact_tcrossprod", (DL_FUNC) &_rpact_tcrossprod, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rpact(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
